// Generated by CoffeeScript 1.6.3
(function() {
  var Body;

  Body = (function() {
    Jitter.Body = Body;

    function Body(stream) {
      this.stream = stream;
    }

    Body.prototype.ready = function(pane, spec) {
      var $e, src;
      src = "img/body/BodyReady.jpg";
      $e = $("<div " + (Jitter.rel(0, 0, 100, 100)) + "></div>");
      $e.append("<h1 " + (Jitter.abs(0, 0, 100, 10)) + ">" + spec.name + "</h1>");
      $e.append("  " + (Jitter.abi(0, 10, 100, 90, src, 150)));
      pane.$.append($e);
    };

    Body.prototype.create = function(pane, spec) {
      var $e, x, y, _i, _j, _len, _len1, _ref, _ref1;
      $e = $("<div   " + (Jitter.rel(0, 0, 100, 100)) + "></div>");
      $e.append("<h1 " + (Jitter.abs(0, 0, 100, 10)) + ">" + spec.name + "</h1>");
      _ref = [10, 55];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        y = _ref[_i];
        _ref1 = [0, 33, 66];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          x = _ref1[_j];
          $e.append("<div " + (Jitter.abs(x, y, 33, 45)) + ">" + x + "</div>");
        }
      }
      pane.$.append($e);
    };

    return Body;

  })();

}).call(this);
