// Generated by CoffeeScript 1.6.3
(function() {
  var Choice;

  Choice = (function() {
    Jitter.Choice = Choice;

    function Choice(stream) {
      this.stream = stream;
    }

    Choice.prototype.ready = function(pane, spec) {
      pane.$.append("<h1>" + spec.name + "</h1>");
    };

    Choice.prototype.create = function(pane, spec) {
      pane.$.append("<h1>" + spec.name + "</h1>");
    };

    return Choice;

  })();

}).call(this);
