// Generated by CoffeeScript 1.6.3
(function() {
  var Coffee;

  Coffee = (function() {
    Jitter.Coffee = Coffee;

    function Coffee(stream) {
      this.stream = stream;
    }

    Coffee.prototype.ready = function(pane, spec) {
      pane.$.append("<h1>" + spec.name + "</h1>");
    };

    Coffee.prototype.create = function(pane, spec) {
      pane.$.append("<h1>" + spec.name + "</h1>");
    };

    return Coffee;

  })();

}).call(this);
