// Generated by CoffeeScript 1.6.3
var Jitter;

Jitter = (function() {
  function Jitter() {}

  Jitter.init = function() {
    Util.ready(function() {
      var page, stream, subjects, ui;
      subjects = ['Select', 'Content', 'Connect', 'Test', 'Plane', 'About', 'Slide', 'Image', 'Cursor', 'Navigate', 'Settings', 'Submit', 'Toggle'];
      stream = new Util.Stream(subjects);
      page = new UI.Page(stream);
      ui = new UI(stream, page);
      Util.noop(ui);
    });
  };

  return Jitter;

})();
