// Generated by CoffeeScript 1.6.3
var Jitter;

Jitter = (function() {
  function Jitter() {}

  Jitter.init = function() {
    Util.ready(function() {
      var page, stream, subjects, ui;
      subjects = ['Select', 'Content', 'Connect', 'Test', 'Plane', 'About', 'Slide', 'Image', 'Cursor', 'Navigate', 'Settings', 'Submit', 'Toggle'];
      stream = new Util.Stream(subjects);
      page = new Jitter.Page(stream);
      ui = new UI(stream, page);
      Util.noop(ui);
    });
  };

  Jitter.abs = function(x, y, w, h) {
    return "style=\"position:absolute; left:" + x + "%; top:" + y + "%; width:" + w + "%; height:" + h + "%; text-align:center; font-size:24px;\" ";
  };

  Jitter.abi = function(x, y, w, h, src, mh, label) {
    var htm;
    if (label == null) {
      label = "";
    }
    htm = "<div     style=\"position:absolute; left:" + x + "%; top:" + y + "%; width:" + w + "%; height:" + h + "%; display:table;\">\n<div   style=\"display:table-cell; vertical-align:middle;\">\n  <img style=\"display:block; margin-left:auto; margin-right:auto; max-height:" + mh + "px;\" src=\"" + src + "\"/>";
    if (Util.isStr(label)) {
      htm += "<div style=\"color:white; font-size:20px; padding-top:4px;\">" + label + "</div>";
    }
    htm += "</div></div>";
    return htm;
  };

  Jitter.rel = function(x, y, w, h) {
    return "style=\"position:relative; left:" + x + "%; top:" + y + "%; width:" + w + "%; height:" + h + "%; text-align:center;\" ";
  };

  Jitter.img = function(src) {
    return "<div style=\"display:table-cell; vertical-align:middle;\"><img style=\"display:block; margin-left:auto; margin-right:auto;\" src=\"" + src + "\"/></div>";
  };

  Jitter.txt = function() {
    return "style=\"color:white; text-align:center;\"  ";
  };

  return Jitter;

})();
