// Generated by CoffeeScript 1.6.3
(function() {
  var Order;

  Order = (function() {
    Jitter.Order = Order;

    function Order(stream) {
      this.stream = stream;
    }

    Order.prototype.ready = function(pane, spec) {
      pane.$.append("<h1>" + spec.name + "</h1>");
    };

    Order.prototype.create = function(pane, spec) {
      pane.$.append("<h1>" + spec.name + "</h1>");
    };

    return Order;

  })();

}).call(this);
