// Generated by CoffeeScript 1.6.3
(function() {
  var Page;

  Page = (function() {
    UI.Page = Page;

    function Page(stream) {
      this.stream = stream;
      this.view = null;
    }

    Page.prototype.ready = function(view, spec) {
      var pane, _i, _len, _ref;
      this.view = view;
      this.spec = spec;
      _ref = this.view.panes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pane = _ref[_i];
        this.createContent(pane, spec[pane.name]);
      }
    };

    Page.prototype.createContent = function(pane, spec) {
      pane.page = this;
      switch (pane.name) {
        case "Flavor":
          this.createFlavor(pane, spec);
          break;
        case "Roast":
          this.createRoast(pane, spec);
          break;
        case "Drink":
          this.createDrink(pane, spec);
          break;
        case "Body":
          this.createBody(pane, spec);
          break;
        case "Brew":
          this.createBrew(pane, spec);
          break;
        case "Aroma":
          this.createAroma(pane, spec);
          break;
        case "Choice":
          this.createChoice(pane, spec);
          break;
        case "Coffee":
          this.createCoffee(pane, spec);
          break;
        case "Order":
          this.createOrder(pane, spec);
          break;
        default:
          Util.error("Page.createContent() unknown pane.name", pane.name);
      }
    };

    Page.prototype.createFlavor = function(pane, spec) {
      pane.$.append("<h1>Flavor</h1>");
    };

    Page.prototype.createRoast = function(pane, spec) {
      pane.$.append("<h1>Roast</h1>");
    };

    Page.prototype.createDrink = function(pane, spec) {
      pane.$.append("<h1>Drink</h1>");
    };

    Page.prototype.createBody = function(pane, spec) {
      pane.$.append("<h1>Body</h1>");
    };

    Page.prototype.createBrew = function(pane, spec) {
      pane.$.append("<h1>Brew</h1>");
    };

    Page.prototype.createAroma = function(pane, spec) {
      pane.$.append("<h1>Aroma</h1>");
    };

    Page.prototype.createChoice = function(pane, spec) {
      pane.$.append("<h1>Choice</h1>");
    };

    Page.prototype.createCoffee = function(pane, spec) {
      pane.$.append("<h1>Coffee</h1>");
    };

    Page.prototype.createOrder = function(pane, spec) {
      pane.$.append("<h1>Order</h1>");
    };

    Page.prototype.selectContent = function(select) {
      switch (select.intent) {
        case UI.SelectOverview:
          this.selectOverview(select);
          break;
        case UI.SelectPractice:
          this.selectPractice(select);
          break;
        case UI.SelectStudy:
          this.selectStudy(select);
          break;
        default:
          Util.error("Page.selectContent() unknown select", select);
      }
    };

    Page.prototype.selectOverview = function(select) {};

    Page.prototype.selectPractice = function(select) {};

    Page.prototype.selectStudy = function(select) {};

    return Page;

  })();

}).call(this);
