// Generated by CoffeeScript 1.6.3
(function() {
  var Page,
    __hasProp = {}.hasOwnProperty;

  Page = (function() {
    UI.Page = Page;

    function Page(stream) {
      this.stream = stream;
      this.view = null;
    }

    Page.prototype.ready = function(view, spec) {
      var pane, _i, _len, _ref;
      this.view = view;
      this.spec = spec;
      _ref = this.view.panes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pane = _ref[_i];
        this.readyContent(pane, spec[pane.name]);
      }
    };

    Page.prototype.readyContent = function(pane, spec) {
      pane.page = this;
      pane.$.empty();
      switch (pane.name) {
        case "Flavor":
          this.readyFlavor(pane, spec);
          break;
        case "Roast":
          this.readyRoast(pane, spec);
          break;
        case "Drink":
          this.readyDrink(pane, spec);
          break;
        case "Body":
          this.readyBody(pane, spec);
          break;
        case "Brew":
          this.readyBrew(pane, spec);
          break;
        case "Aroma":
          this.readyAroma(pane, spec);
          break;
        case "Choice":
          this.readyChoice(pane, spec);
          break;
        case "Coffee":
          this.readyCoffee(pane, spec);
          break;
        case "Order":
          this.readyOrder(pane, spec);
          break;
        default:
          Util.error("Page.createContent() unknown pane.name", pane.name);
      }
    };

    Page.prototype.readyFlavor = function(pane, spec) {
      var $e, src;
      pane.$.append("<h1>" + spec.name + "</h1>");
      $e = $("<div style=\"position:relative; width:100%; height:100%;\"></div>");
      src = "img/flavor/FlavorReady.png";
      $e.append("<img style=\"display:block; margin-left:auto; margin-right:auto; vertical-align:middle;\" src=\"" + src + "\"/>");
      pane.$.append($e);
    };

    Page.prototype.readyRoast = function(pane, spec) {
      var $e, src;
      pane.$.append("<h1>" + spec.name + "</h1>");
      $e = $("<div style=\"position:relative; width:100%; height:100%;\"></div>");
      src = "img/roast/Coffee-Bean-Roast-Ready.jpg";
      $e.append("<img style=\"display:block; margin-left:auto; margin-right:auto; vertical-align:middle;\" src=\"" + src + "\"/>");
      pane.$.append($e);
    };

    Page.prototype.readyDrink = function(pane, spec) {
      var $e, src;
      pane.$.append("<h1>" + spec.name + "</h1>");
      $e = $("<div style=\"position:relative; width:100%; height:100%;\"></div>");
      src = "img/drink/DrinkReady.jpg";
      $e.append("<img style=\"display:block; margin-left:auto; margin-right:auto; vertical-align:middle;\" src=\"" + src + "\"/>");
      pane.$.append($e);
    };

    Page.prototype.readyBody = function(pane, spec) {
      var $e, src;
      pane.$.append("<h1>" + spec.name + "</h1>");
      $e = $("<div style=\"position:relative; width:100%; height:100%;\"></div>");
      src = "img/body/BodyReady.jpg";
      $e.append("<img style=\"display:block; margin-left:auto; margin-right:auto; vertical-align:middle;\" src=\"" + src + "\"/>");
      pane.$.append($e);
      return;
    };

    Page.prototype.readyBrew = function(pane, spec) {
      var $e, src;
      pane.$.append("<h1>" + spec.name + "</h1>");
      $e = $("<div style=\"position:relative; width:100%; height:100%;\"></div>");
      src = "img/brew/" + spec['AutoDrip'].icon;
      $e.append("<img style=\"display:block; margin-left:auto; margin-right:auto; vertical-align:middle;\" src=\"" + src + "\"/>");
      pane.$.append($e);
    };

    Page.prototype.readyAroma = function(pane, spec) {
      var $e, src;
      pane.$.append("<h1>" + spec.name + "</h1>");
      $e = $("<div style=\"position:relative; width:100%; height:100%;\"></div>");
      src = "img/aroma/AromaReady.png";
      $e.append("<img style=\"display:block; margin-left:auto; margin-right:auto; vertical-align:middle;\" src=\"" + src + "\"/>");
      pane.$.append($e);
    };

    Page.prototype.readyChoice = function(pane, spec) {
      pane.$.append("<h1>" + spec.name + "</h1>");
    };

    Page.prototype.readyCoffee = function(pane, spec) {
      pane.$.append("<h1>" + spec.name + "</h1>");
    };

    Page.prototype.readyOrder = function(pane, spec) {
      pane.$.append("<h1>" + spec.name + "</h1>");
    };

    Page.prototype.onSelect = function(pane, select) {
      UI.verifySelect(select, 'Page');
      switch (select.intent) {
        case UI.SelectOverview:
          this.selectOverview();
          break;
        case UI.SelectPractice:
          this.selectPractice(pane);
          break;
        case UI.SelectStudy:
          this.selectStudy(pane);
          break;
        default:
          Util.error("Page.selectContent() unknown select", select);
      }
    };

    Page.prototype.selectOverview = function() {
      var pane, _i, _len, _ref, _results;
      _ref = this.view.panes;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pane = _ref[_i];
        _results.push(this.readyContent(pane, this.spec[pane.name]));
      }
      return _results;
    };

    Page.prototype.selectPractice = function(pane) {
      return this.createContent(pane, this.spec[pane.name]);
    };

    Page.prototype.selectStudy = function(pane) {
      Util.noop(pane);
    };

    Page.prototype.createContent = function(pane, spec) {
      pane.$.empty();
      switch (pane.name) {
        case "Flavor":
          this.createFlavor(pane, spec);
          break;
        case "Roast":
          this.createRoast(pane, spec);
          break;
        case "Drink":
          this.createDrink(pane, spec);
          break;
        case "Body":
          this.createBody(pane, spec);
          break;
        case "Brew":
          this.createBrew(pane, spec);
          break;
        case "Aroma":
          this.createAroma(pane, spec);
          break;
        case "Choice":
          this.createChoice(pane, spec);
          break;
        case "Coffee":
          this.createCoffee(pane, spec);
          break;
        case "Order":
          this.createOrder(pane, spec);
          break;
        default:
          Util.error("Page.createContent() unknown pane.name", pane.name);
      }
    };

    Page.prototype.createFlavor = function(pane, spec) {
      UI.plotId = "FlavorVisual";
      UI.jsonD3 = "json/flavor.jitter.json";
      pane.$.append("<h1>" + spec.name + "</h1>");
      pane.$.append("<div id=\"" + UI.plotId + "\">&nbsp;</div>");
      Util.loadScript("js/wheel/flavor.v3.js");
    };

    Page.prototype.createRoast = function(pane, spec) {
      var $e, src;
      pane.$.append("<h1>" + spec.name + "</h1>");
      $e = $("<div style=\"position:relative; width:100%; height:100%;\"></div>");
      src = "img/roast/FiveRoasts.jpeg";
      $e.append("<img style=\"display:block; margin-left:auto; margin-right:auto; vertical-align:middle;\" src=\"" + src + "\"/>");
      pane.$.append($e);
    };

    Page.prototype.pos = function(x, y, w, h) {
      return "position:absolute; left:" + x + "%; top:" + y + "%; width:" + w + "%; height:" + h + "%; text-align:center;";
    };

    Page.prototype.createDrink = function(pane, spec) {
      var $e, x, y, _i, _j, _len, _len1, _ref, _ref1;
      $e = $("<div style=\"position:relative; width:100%; height:100%;\"></div>");
      $e.append("<h1 style=\"" + (this.pos(0, 0, 100, 10)) + "\">" + spec.name + "</h1>");
      _ref = [10, 55];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        y = _ref[_i];
        _ref1 = [0, 33, 66];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          x = _ref1[_j];
          $e.append("<div style=\"" + (this.pos(x, y, 33, 45)) + "\">" + x + "</div>");
        }
      }
      pane.$.append($e);
    };

    Page.prototype.createBody = function(pane, spec) {
      var $e, x, y, _i, _j, _len, _len1, _ref, _ref1;
      $e = $("<div style=\"position:relative; width:100%; height:100%;\"></div>");
      $e.append("<h1 style=\"" + (this.pos(0, 0, 100, 10)) + "\">" + spec.name + "</h1>");
      _ref = [10, 55];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        y = _ref[_i];
        _ref1 = [0, 33, 66];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          x = _ref1[_j];
          $e.append("<div style=\"" + (this.pos(x, y, 33, 45)) + "\">" + x + "</div>");
        }
      }
      pane.$.append($e);
      return;
    };

    Page.prototype.createBrew = function(pane, spec) {
      var $e, brew, h, i, key, src, w, x, y;
      pane.$.append("<h1>Brew</h1>");
      $e = $("<div style=\"position:relative; width:100%; height:100%;\"></div>");
      i = 1;
      x = 0;
      w = 25;
      h = 25;
      for (key in spec) {
        if (!__hasProp.call(spec, key)) continue;
        brew = spec[key];
        if (!(UI.isChild(key))) {
          continue;
        }
        src = 'img/brew/' + brew.icon;
        x = i !== 4 ? x + 25 : 0;
        y = i <= 4 ? 10 : 50;
        if (i === 5) {
          x = 12.5;
        }
        $e.append("<div style=\"position:absolute; left:" + x + "%; top:" + y + "%; width:" + w + "%; height:" + h + "%;\">\n  <img style=\"display:block; margin-left:auto; margin-right:auto;\" src=\"" + src + "\"/>\n  <div style=\"color:white; text-align:center;\">" + brew.name + "</div></div>\n</div>");
        i = i + 1;
      }
      pane.$.append($e);
    };

    Page.prototype.createAroma = function(pane, spec) {
      UI.plotId = "AromaVisual";
      UI.jsonD3 = "json/aroma.json";
      pane.$.append("<h1>" + spec.name + "</h1>");
      pane.$.append("<div id=\"" + UI.plotId + "\">&nbsp;</div>");
      Util.loadScript("js/wheel/flavor.v3.js");
    };

    Page.prototype.createChoice = function(pane, spec) {
      pane.$.append("<h1>" + spec.name + "</h1>");
    };

    Page.prototype.createCoffee = function(pane, spec) {
      pane.$.append("<h1>" + spec.name + "</h1>");
    };

    Page.prototype.createOrder = function(pane, spec) {
      pane.$.append("<h1>" + spec.name + "</h1>");
    };

    return Page;

  })();

}).call(this);
