// Generated by CoffeeScript 1.6.3
(function() {
  var Roast;

  Roast = (function() {
    Jitter.Roast = Roast;

    function Roast(stream) {
      this.stream = stream;
    }

    Roast.prototype.ready = function(pane, spec) {
      var $e, src;
      src = "img/roast/Coffee-Bean-Roast-Ready.jpg";
      $e = $("<div " + (Jitter.rel(0, 0, 100, 100)) + "></div>");
      $e.append("<h1 " + (Jitter.abs(0, 0, 100, 10)) + ">" + spec.name + "</h1>");
      $e.append("  " + (Jitter.abi(0, 10, 100, 90, src, 150)));
      pane.$.append($e);
    };

    Roast.prototype.create = function(pane, spec) {
      var $e, src;
      pane.$.append("<h1>" + spec.name + "</h1>");
      $e = $("<div " + (Jitter.rel(0, 0, 100, 100)) + "></div>");
      src = "img/roast/FiveRoasts.jpeg";
      $e.append("<img " + (Jitter.img(src)) + "/>");
      pane.$.append($e);
    };

    return Roast;

  })();

}).call(this);
